---
- name: Update apt-get repo and cache
  apt: 
    update_cache: yes
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add key repo
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

- name: Add repo 
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update update repo and install docker
  apt: 
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io 


- name: test docker
  shell: "docker run hello-world"